version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      - POSTGRES_DB=postgress
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - local_rag
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - local_rag
    restart: unless-stopped

volumes:
  timescaledb_data:
  ollama:

networks:
  local_rag:
    driver: bridge